### ISSUE TITLE
Plugin Restrict Email Domains

### ISSUE THREAD

**Issue by Pichorka** [MattRogowski/Restrict-Email-Domains#2]
Hello,  

Could you please add a window or explanatory message on these restrictions, and to the person who can not register with an official mail from his / her internet or mobile operator in his / her country, to contact through a contact link , The webmaster in order to ask the authorization of domain @domaine. Country, landline or mobile?  

Best regards,

**Comment by MattRogowski** [comment]
You could add this by editing ./inc/languages/english/restrictemaildomains.lang.php and add in the message you would like, and it will then appear in the validation message the user sees when they use a disallowed email address.
